DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE usergroup (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE gamesubmit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  game_tag TEXT NOT NULL,
  score TEXT NOT NULL,
  FOREIGN KEY (group_id) REFERENCES usergroup (id)
);